-- Work Tracker: add employee-code login + import full roster.
-- Run ONCE in the Neon SQL Editor on your existing database. Safe to re-run.
-- Lets people log in with email OR employee code; adds the 4 staff who have no email.

-- 1) schema: email becomes optional, add the emp_code column + unique index
ALTER TABLE users ALTER COLUMN email DROP NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS emp_code VARCHAR(40);
CREATE UNIQUE INDEX IF NOT EXISTS ix_users_emp_code ON users (emp_code);

-- 2) staff WITH email: insert if missing, else just backfill their emp code
--    (existing rows keep their current password, name and role)
INSERT INTO users (emp_code, email, name, whatsapp, role, password_hash, must_reset, active) VALUES ('BSC/003', 'purchase@bharatsteels.in', 'MURKESH M.P.R', '919444085020', 'user', '$2b$12$jmOxLfS/56fIwDUPuIW6du00sEvPM0M5Dvo4fycArZP/VC3y40KNS', true, true) ON CONFLICT (email) DO UPDATE SET emp_code = EXCLUDED.emp_code;
INSERT INTO users (emp_code, email, name, whatsapp, role, password_hash, must_reset, active) VALUES ('BSC/006', 'baktha@bharatsteels.in', 'BAKTHAVACHALAM C', '919444085016', 'user', '$2b$12$jmOxLfS/56fIwDUPuIW6du00sEvPM0M5Dvo4fycArZP/VC3y40KNS', true, true) ON CONFLICT (email) DO UPDATE SET emp_code = EXCLUDED.emp_code;
INSERT INTO users (emp_code, email, name, whatsapp, role, password_hash, must_reset, active) VALUES ('BSC/074', 'connect@bharatsteels.in', 'SUSMITHA AVULA', '916281867026', 'user', '$2b$12$jmOxLfS/56fIwDUPuIW6du00sEvPM0M5Dvo4fycArZP/VC3y40KNS', true, true) ON CONFLICT (email) DO UPDATE SET emp_code = EXCLUDED.emp_code;
INSERT INTO users (emp_code, email, name, whatsapp, role, password_hash, must_reset, active) VALUES ('BSC/098', 'kannan@bharatsteels.in', 'KANNAN K', '919840299625', 'user', '$2b$12$jmOxLfS/56fIwDUPuIW6du00sEvPM0M5Dvo4fycArZP/VC3y40KNS', true, true) ON CONFLICT (email) DO UPDATE SET emp_code = EXCLUDED.emp_code;
INSERT INTO users (emp_code, email, name, whatsapp, role, password_hash, must_reset, active) VALUES ('BSC/119', 'jeeva@bharatsteels.in', 'JEEVABHARATHY S', '917395956648', 'superadmin', '$2b$12$jmOxLfS/56fIwDUPuIW6du00sEvPM0M5Dvo4fycArZP/VC3y40KNS', true, true) ON CONFLICT (email) DO UPDATE SET emp_code = EXCLUDED.emp_code;
INSERT INTO users (emp_code, email, name, whatsapp, role, password_hash, must_reset, active) VALUES ('BSC/136', 'sap@bharatsteels.in', 'NAGASUBRAMANIAN N', '919894174741', 'user', '$2b$12$jmOxLfS/56fIwDUPuIW6du00sEvPM0M5Dvo4fycArZP/VC3y40KNS', true, true) ON CONFLICT (email) DO UPDATE SET emp_code = EXCLUDED.emp_code;
INSERT INTO users (emp_code, email, name, whatsapp, role, password_hash, must_reset, active) VALUES ('BSC/160', 'hr@bharatsteels.in', 'RAJASEKAR', '918825849418', 'user', '$2b$12$jmOxLfS/56fIwDUPuIW6du00sEvPM0M5Dvo4fycArZP/VC3y40KNS', true, true) ON CONFLICT (email) DO UPDATE SET emp_code = EXCLUDED.emp_code;
INSERT INTO users (emp_code, email, name, whatsapp, role, password_hash, must_reset, active) VALUES ('CEO', 'gourav@bharatsteels.in', 'GOURAV SARAF', '919884696666', 'superadmin', '$2b$12$jmOxLfS/56fIwDUPuIW6du00sEvPM0M5Dvo4fycArZP/VC3y40KNS', true, true) ON CONFLICT (email) DO UPDATE SET emp_code = EXCLUDED.emp_code;
INSERT INTO users (emp_code, email, name, whatsapp, role, password_hash, must_reset, active) VALUES ('CMD', 'cmd@bharatsteels.in', 'GOVERDHAN AGARWAL', '919444088086', 'superadmin', '$2b$12$jmOxLfS/56fIwDUPuIW6du00sEvPM0M5Dvo4fycArZP/VC3y40KNS', true, true) ON CONFLICT (email) DO UPDATE SET emp_code = EXCLUDED.emp_code;
INSERT INTO users (emp_code, email, name, whatsapp, role, password_hash, must_reset, active) VALUES ('G2S/058', 'ganapathy@bharatsteels.in', 'GANAPATHY P', '919840630463', 'user', '$2b$12$jmOxLfS/56fIwDUPuIW6du00sEvPM0M5Dvo4fycArZP/VC3y40KNS', true, true) ON CONFLICT (email) DO UPDATE SET emp_code = EXCLUDED.emp_code;
INSERT INTO users (emp_code, email, name, whatsapp, role, password_hash, must_reset, active) VALUES ('TECH', 'inspace_it@bharatsteels.in', 'MOHAN', '919384819376', 'user', '$2b$12$jmOxLfS/56fIwDUPuIW6du00sEvPM0M5Dvo4fycArZP/VC3y40KNS', true, true) ON CONFLICT (email) DO UPDATE SET emp_code = EXCLUDED.emp_code;
INSERT INTO users (emp_code, email, name, whatsapp, role, password_hash, must_reset, active) VALUES ('MET106', 'accounts@metfraa.com', 'BALAJI M', '918637466998', 'user', '$2b$12$jmOxLfS/56fIwDUPuIW6du00sEvPM0M5Dvo4fycArZP/VC3y40KNS', true, true) ON CONFLICT (email) DO UPDATE SET emp_code = EXCLUDED.emp_code;
INSERT INTO users (emp_code, email, name, whatsapp, role, password_hash, must_reset, active) VALUES ('MET66', 'admin@metfraa.com', 'BODAPATI SHEELA HEPSIBAH GRACE', '919963315234', 'user', '$2b$12$jmOxLfS/56fIwDUPuIW6du00sEvPM0M5Dvo4fycArZP/VC3y40KNS', true, true) ON CONFLICT (email) DO UPDATE SET emp_code = EXCLUDED.emp_code;
INSERT INTO users (emp_code, email, name, whatsapp, role, password_hash, must_reset, active) VALUES ('MET110', 'vp@metfraa.com', 'KALAI BRINDHA M P', '919600068189', 'user', '$2b$12$jmOxLfS/56fIwDUPuIW6du00sEvPM0M5Dvo4fycArZP/VC3y40KNS', true, true) ON CONFLICT (email) DO UPDATE SET emp_code = EXCLUDED.emp_code;
INSERT INTO users (emp_code, email, name, whatsapp, role, password_hash, must_reset, active) VALUES ('MET51', 'khajasheriff.m@metfraa.com', 'KHAJA SHERIFF', '917010507589', 'user', '$2b$12$jmOxLfS/56fIwDUPuIW6du00sEvPM0M5Dvo4fycArZP/VC3y40KNS', true, true) ON CONFLICT (email) DO UPDATE SET emp_code = EXCLUDED.emp_code;
INSERT INTO users (emp_code, email, name, whatsapp, role, password_hash, must_reset, active) VALUES ('MET78', 'nirmal@metfraa.com', 'NIRMAL KUMAR BALAKRISHNAN', '919840485801', 'user', '$2b$12$jmOxLfS/56fIwDUPuIW6du00sEvPM0M5Dvo4fycArZP/VC3y40KNS', true, true) ON CONFLICT (email) DO UPDATE SET emp_code = EXCLUDED.emp_code;
INSERT INTO users (emp_code, email, name, whatsapp, role, password_hash, must_reset, active) VALUES ('MET64', 'thangaraj@metfraa.com', 'P. THANGARAJ', '919994086097', 'user', '$2b$12$jmOxLfS/56fIwDUPuIW6du00sEvPM0M5Dvo4fycArZP/VC3y40KNS', true, true) ON CONFLICT (email) DO UPDATE SET emp_code = EXCLUDED.emp_code;
INSERT INTO users (emp_code, email, name, whatsapp, role, password_hash, must_reset, active) VALUES ('MET92', 'varadharaj@metfraa.com', 'VARATHARAJ NAVANEETHAN', '919790249180', 'user', '$2b$12$jmOxLfS/56fIwDUPuIW6du00sEvPM0M5Dvo4fycArZP/VC3y40KNS', true, true) ON CONFLICT (email) DO UPDATE SET emp_code = EXCLUDED.emp_code;
INSERT INTO users (emp_code, email, name, whatsapp, role, password_hash, must_reset, active) VALUES ('MET-MD', 'arasu@metfraa.com', 'VELARASU', '919787720731', 'superadmin', '$2b$12$jmOxLfS/56fIwDUPuIW6du00sEvPM0M5Dvo4fycArZP/VC3y40KNS', true, true) ON CONFLICT (email) DO UPDATE SET emp_code = EXCLUDED.emp_code;

-- 3) staff with NO email: they sign in with their employee code
INSERT INTO users (emp_code, name, whatsapp, role, password_hash, must_reset, active) VALUES ('BSC/004', 'NALLASIVAM D', '919444085018', 'user', '$2b$12$jmOxLfS/56fIwDUPuIW6du00sEvPM0M5Dvo4fycArZP/VC3y40KNS', true, true) ON CONFLICT (emp_code) DO NOTHING;
INSERT INTO users (emp_code, name, whatsapp, role, password_hash, must_reset, active) VALUES ('BSC/005', 'PARAMAGURU S', '919444085015', 'user', '$2b$12$jmOxLfS/56fIwDUPuIW6du00sEvPM0M5Dvo4fycArZP/VC3y40KNS', true, true) ON CONFLICT (emp_code) DO NOTHING;
INSERT INTO users (emp_code, name, whatsapp, role, password_hash, must_reset, active) VALUES ('BSC/012', 'VENKATESH PRASAD DOBA', '917200006787', 'user', '$2b$12$jmOxLfS/56fIwDUPuIW6du00sEvPM0M5Dvo4fycArZP/VC3y40KNS', true, true) ON CONFLICT (emp_code) DO NOTHING;
INSERT INTO users (emp_code, name, whatsapp, role, password_hash, must_reset, active) VALUES ('BSC/017', 'SHIVAM SHROFF', '919884384261', 'user', '$2b$12$jmOxLfS/56fIwDUPuIW6du00sEvPM0M5Dvo4fycArZP/VC3y40KNS', true, true) ON CONFLICT (emp_code) DO NOTHING;
